INSERT INTO USERS (LOGIN, PASSWORD) VALUES ('aa1', '$2a$10$CykSaV8e10pqThAz/ozpHucOETUlcpaGhckqz/NDoc36d6DVccqRq');
INSERT INTO USERS (LOGIN, PASSWORD) VALUES ('bb1', '$2a$10$yXiqM776jT1h58BkdxMKIuYF4la3KPKrFHBzFK8l7vbFyopdj9CyO');

INSERT INTO ACCOUNTS (BALANCE, USER) VALUES ('1000', 'aa1');
INSERT INTO ACCOUNTS (BALANCE, USER) VALUES ('593', 'aa1');
INSERT INTO ACCOUNTS (BALANCE, USER) VALUES ('10', 'aa1');
INSERT INTO ACCOUNTS (BALANCE, USER) VALUES ('99', 'bb1');
INSERT INTO ACCOUNTS (BALANCE, USER) VALUES ('176', 'bb1');